name: build
on:
  push:
    branches:
      - master
      - dev
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - run: make test-all
